# Generated by Django 4.1.2 on 2022-11-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_data_added_topic_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizaeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_size', models.CharField(max_length=200)),
                ('p_quantity', models.IntegerField()),
                ('p_details', models.TextField()),
            ],
        ),
    ]
